[package]
name = "ray_caster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.9.0"
winit = "0.26"


[[bin]]
name = "ray_caster"
path = "main.rs"
